import { IframeState } from '../IframeState/IframeState.ts'
import * as IframeStates from '../IframeStates/IframeStates.ts'

// TODO parentUid might ot be needed
export const create = (
  id: number,
  uri: string,
  x: number,
  y: number,
  width: number,
  height: number,
  args: any,
  parentUid: any,
  platform: number = 0,
  assetDir: string = '',
): void => {
  const state: IframeState = {
    assetDir,
    confirmDelete: false,
    confirmPaste: false,
    cutItems: [],
    decorations: [],
    deltaY: 0,
    dropTargets: [],
    editingErrorMessage: '',
    editingIcon: '',
    editingIndex: -1,
    editingSelectionEnd: 0,
    editingSelectionStart: 0,
    editingValue: '',
    errorMessageLeft: 0,
    errorMessageTop: 0,
    errorMessageWidth: 0,
    excluded: [],
    fileIconCache: Object.create(null),
    finalDeltaY: 0,
    focus: 0,
    focused: false,
    focusedIndex: -1,
    focusWord: '',
    focusWordTimeout: 800,
    handleOffset: 0,
    height,
    hoverIndex: -1,
    icons: [],
    initial: false,
    inputSource: 0,
    isPointerDown: false,
    items: [],
    maxIndent: 0,
    maxLineY: 0,
    minLineY: 0,
    parentUid,
    pasteShouldMove: false,
    platform,
    pointerDownIndex: -1,
    root: '',
    scrollBarActive: false,
    scrollBarHeight: 0,
    sourceControlDecorations: false,
    sourceControlIgnoredUris: [],
    uid: id,
    useChevrons: false,
    version: 0,
    visibleExplorerItems: [],
    width,
    x,
    y,
  }
  IframeStates.set(state.uid, state, state)
  return state
}
